use_frameworks!

platform :ios, '9.0'

target 'BGEModularControl_Example' do
  pod 'BGEModularControl', :path => '../'

  target 'BGEModularControl_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
